#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from tenji import TENJI_MAP

def run():
    while True:
        display_str = '日本語かなを入力してください> '
        raw_input_str = input(display_str)

        if raw_input_str == 'q':
            break
        input_str = raw_input_str
        output_str = ''
        i = 0
        while i < len(input_str):
            if TENJI_MAP.get(input_str[i:i+2]):
                output_str += TENJI_MAP.get(input_str[i:i+2])
                i += 1
            else:
                output_str += TENJI_MAP[input_str[i]]
            i += 1
        output_str += '\n'
        print(output_str)

run()
